server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
  datasource:
    username : root
    password : wang1992
    url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name : com.mysql.cj.jdbc.Driver
    type : com.alibaba.druid.pool.DruidDataSource
    druid :
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    #cache-enabled: true
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    com.example.demo.dao : debug